### ISSUE TITLE
[Feature Request] Standardize metadata sheetnames

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ARCtrl#179]
Currently `isa_study` and `isa_assay` for study and assay files respectively, but `Investigation` instead of `isa_investigation`.

@omaus @kMutagene

**Comment by omaus** [comment]
Why is that? Why do they differ?

**Comment by HLWeil** [comment]
Why is the banana krumm?

**Comment by kMutagene** [comment]
> Why is that? Why do they differ?

I guess because someone dared to make an error. shame on them.

Offending line is here: 

https://github.com/nfdi4plants/ARCtrl/blob/e9e8e2e0b0fa710d4767efdee623ea7c47192f39/src/ISA/ISA.Spreadsheet/InvestigationFile/Investigation.fs#L205

Going by discussion of #138, the name should be `isa_investigation` @HLWeil ?

**Comment by HLWeil** [comment]
> > Why is that? Why do they differ?
> 
> I guess because someone dared to make an error. shame on them.
> 
> Offending line is here:
> 
> https://github.com/nfdi4plants/ARCtrl/blob/e9e8e2e0b0fa710d4767efdee623ea7c47192f39/src/ISA/ISA.Spreadsheet/InvestigationFile/Investigation.fs#L205
> 
> Going by discussion of #138, the name should be `isa_investigation` @HLWeil ?

Yes exactly, already fixed locally, writing tests now.

**Comment by omaus** [comment]
> Why is the banana krumm?

Ah sry, I thought that the difference was intended instead of being a mistake. No prob.

**Comment by Freymaurer** [comment]
Implemented on Developer ✨ by @HLWeil
