### ISSUE TITLE
[Feature Request] Add building block type "Comment"? 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/ARCtrl#261]
Might make sense to implement ISA's "comment" building block type to allow additional ISA-conform annotation. 

Use-case: An assay failed. How to annotate that per process / sample / file?

**Comment by HLWeil** [comment]
Might also be of interest for @Hannah-Doerpholz

**Comment by HLWeil** [comment]
We can definitely think about adding comments. But I don't quite get your `Use-case` 😅

**Comment by Brilator** [comment]
I measure something in the lab and create a dataset where 5 out of 20 "raw data files" should not be used for downstream analysis, because something went wrong in the lab. 

- Option 1: delete them from dataset and isa.assay and pretend they never existed (that's the typical "publication" way) 
- Option 2: mention that they are not of good quality for reason xy (-> comment) 

Option 2 is required by e.g. core facilities that routinely measure some data and need to discuss the outcome including failures.

**Comment by HLWeil** [comment]
👍 
Technically I don't see a counter-argument and there seem to be some use-cases.

**Comment by patrick-koenig** [comment]
Since the use of comments within ISA is also necessary for the currently valid MIAPPE checklist mapping v1.1 (and cannot be completely avoided even with a new eventually improved mapping), I can only support the general support of ISA-comments in ARCtrl. @Brilator's use case also seems to make perfect sense to me.

**Comment by andreaschrader** [comment]
👍  also from OMERO-ARC interoperability work: Would also be supportive for our mapping of some REMBI terms to ARC (ISA) supporting RDM-compliant annotation of imaging data in ARCs.

**Comment by Freymaurer** [comment]
Is it expected to just be 

|Comment|
|----------------|
|any information|

**Comment by Brilator** [comment]
I would strongly recommend not to try and map anything to “comment” (as opposed to anything ontology backed). That’s one lesson learned from MIAPPE to ISA. 
So IMO this is really more to support user flexibility.

**Comment by andreaschrader** [comment]
For the case I am referring to, Comment[REMBI-specific_term] was the envisioned solution and than passing a semicolon separated list from the same Swate sheet to the cells below, if possible. The few "REMBI-specific_term"s for which this solution would be required could be added, where not available yet, to an ontology.

Suggestion: Comment[User_comment] or even more specific Comment[failed_assay] etc. could be used either for a flexible user comment or to specify a user comment type.

**Comment by Freymaurer** [comment]
So it is more of type:

|Comment [failed assay] |
|:-----------|
| any information |
| more information |
| and more information |
| finally more information |

where `failed assay` is an ontology term?

**Comment by HLWeil** [comment]
It would be a key-value pair with both being strings.

**Comment by HLWeil** [comment]
Matching the isa-json comment:
https://isa-specs.readthedocs.io/en/latest/isajson.html#comment-schema-json

**Comment by HLWeil** [comment]
I agree with @Brilator, that we should try to minimize using comments for mapping. 

In the case you mentioned though, @andreaschrader, you actually map a comment in REMBI to a comment in ISA, right? This would actually be a proper direct mapping.

In another case we discussed in person last week, the mapping would be done with structured fields supported by controlled vocabulary (REMBI: experimental_variable <-> ISA: Factor). But the comments would be used to add mapping details between the two. Any documentation you could point to on this train of thought, @andreaschrader & @kMutagene?

**Comment by andreaschrader** [comment]
> So it is more of type:
> Comment [failed assay]
> any information
> more information
> and more information
> finally more information
> 
> where `failed assay` is an ontology term?

I could envision 'User_comment' to be a flexible free text comment a user can use to annotate failed samples or other so far uncovered information relevant as requested above. It also might be another term the other use case prefers instead of 'Comment[User_comment]' - maybe even 'Comment[free text]' or for some more intuitive just 'Comment[]' is an option?

This way the column Comment[User_comment] could look like this:
 
|Comment[User_comment]|
|---|
|any information|
|flexible user information|
|and more information|

but it could also be more specific like 

|Comment[failed_assay]|
|---|
|broken tube|
|pipetting error|
|or just "yes" or "True"|

'failed_assay' MAY be an ontology term (OPTIONAL)

In the case of my example, REMBI-specific_term would be a fixed term and would be used repetitively and thereby could at least as a header be defined as an ontology term.

|Comment[REMBI-specific_term]|
|--|
|Factor[age], Factor[genotype]|
|Factor[age], Factor[genotype]| 

This way the user has the flexibility to use Comment with and without ontology term enabling users (OPTIONAL) to make even their comments machine readable.

**Comment by andreaschrader** [comment]
> I agree with @Brilator, that we should try to minimize using comments for mapping.
> 
> In the case you mentioned though, @andreaschrader, you actually map a comment in REMBI to a comment in ISA, right? This would actually be a proper direct mapping.
> 
> In another case we discussed in person last week, the mapping would be done with structured fields supported by controlled vocabulary (REMBI: experimental_variable <-> ISA: Factor). But the comments would be used to add mapping details between the two. Any documentation you could point to on this train of thought, @andreaschrader & @kMutagene?

Yes @HLWeil we had discussed both cases you mentioned above. The latter was the case I was referring to. Documentation in progress. In this current branch in the report on slide 8 is the respective example: https://github.com/NFDI4BIOIMAGE/BHG2023-OMERO-ARC/blob/reporting/Reporting/BioHack_2023_Final_OMERO_ARC.pdf
