### ISSUE TITLE
[Feature Request] improve build chain syntax

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#280]
Just saw @MangelMaxime's beatiful implementation for fake targets (code below, taken from thoth.json feature/future branch). As this project becomes quite large we could benefit from a similiar structure to better clarify these targets.

```f#
[<EntryPoint>]
let main argv =
    let argv = argv |> Array.map (fun x -> x.ToLower()) |> Array.toList

    Command.Run("dotnet", "husky install")

    match argv with
    | "test" :: args ->
        match args with
        | "legacy" :: args -> Test.Legacy.handle args
        | "javascript" :: args -> Test.JavaScript.handle args
        | "newtonsoft" :: args -> Test.Newtonsoft.handle args
        | "python" :: args -> Test.Python.handle args
        | []
        | "all" :: _ ->
            Test.JavaScript.handle []
            Test.Newtonsoft.handle []
            Test.Python.handle []
        | _ -> printHelp ()
    | "publish" :: args -> Publish.handle args
    | "help" :: _
    | "--help" :: _
    | _ -> printHelp ()
```

**Comment by MangelMaxime** [comment]
Thank you 🙏

Another alternative to FAKE, is [Fun.Build](https://github.com/slaveOftime/Fun.Build). I used it several time in the past and it goes a great job for simple pipelines.

[Fable REPL](https://github.com/fable-compiler/repl/blob/cac14fb749e80c2d6cb3f7d57a9feb6cfbf40947/build.fsx).

I don't always use it because in some projects like Fable or Thoth.Json I need the code to work in a specific way which is not how Fun.Build envision the code to be.
