### ISSUE TITLE
No Additional Property Data Columns are created, when a data cell is converted into excel values

### ISSUE THREAD

**Issue by Etschbeijer** [nfdi4plants/ARCtrl#466]
**Describe the bug**
Currently, when an arc table data cell is converted into excel values, no additional proeprty data columns are generated because those must exist beforehand (based on the current code, see snippet)

**To Reproduce**
1. Create Annotation Table in Excel
2. Rename Column to Output / Input [Data]
3. Click the convert button in the Building Blocks slide of Swate - Excel
4. No Additional Data Columns are generated, only the Column Name is changed

**Expected behavior**
When an Input / Ouptut freetext cell is converted into a data cell, the additional property data columns shall be created. When all cells are freetext, the additional property data columns shall not be added but when at least one cell is data, the additional property data columns shall be added.

**Screenshots**
![Image](https://github.com/user-attachments/assets/1c594d68-e96f-46a6-8350-bd46807862a0)

property data columns
![Image](https://github.com/user-attachments/assets/6e3e9e5c-0802-43f8-a558-992a62c2ec4e)

**Comment by Freymaurer** [comment]
To add additional information:

Swate in Excel wants to give the user the option to convert their "Output/Input [Data]" columns to have data cells or freetext cells.

Currently. If these cells are transformed to Data cells they are "empty" data cells as the user was not yet able to create any data specific information. Due to the cells not having `Format` or `SelectorFormat`, the columns are not created. 

If there is no reason for the `if hasFormat` and `if hasSelectorFormat` conditions they should be removed to enable this functionality for Swate in Excel.
