### ISSUE TITLE
[BUG] Assay: Different values for a Characteristic for the same Source Name should not be possible

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ARCtrl#57]
**Describe the bug**
When creating an Assay and set several rows with the same Source Name, it should not be possible to set different Values for a Characteristic, but it is atm.

**To Reproduce**
1. Create an Assay with a Swate table
2. Add Characteristic `MyCharacteristic 1`
3. Write `MySource` in the first value row for column Source Name
4. Write the same in the second row
5. Write `value 1` in the first value row for column `My Characteristic 1`
6. Write `value 2` in the second value row for column `My Characteristic 1` (see screenshot below for steps 2 – 6)
7. Parse with common ISA.NET functions
8. Notice that there are several inputs with different Characteristics yet with the same name

**Expected behavior**
Forbid this (via, e.g., throwing an error or sth. alike).

**Screenshots**
![image](https://user-images.githubusercontent.com/47781170/161598595-799fa520-66a6-4c0e-a22d-63936c1b488a.png)

**Comment by muehlhaus** [comment]
I think the expected behavior of a reader should be that as long as the format schema is valid the file should be readable (for example also to potentially autocorrect or automated content testing). NO warning or exception should be thrown based on content testing. Here, we want to separate checking potential rules (e.g. ARC, ISA, ...) from parsing and management whenever possible...

**Comment by muehlhaus** [comment]
I think the situation increases the need for a separate content validator.

**Comment by HLWeil** [comment]
Following @muehlhaus' suggestions. I will switch the tagging. I'm also not sure whether this remains a thing for ISADotNet or for the ArcCommander, so the Issue could potentially also be moved.
